version: "3"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: npm run start
    volumes:
      - .:/app
    ports:
      - "5000:5000"
